services:
    # Only sonata admin services here
    admin.user:
        class: AppBundle\Controller\SonataAdmin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Пользователи' }

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
sonata_admin:
    title: 'Test Title'
    templates:
        layout: '@App/SonataAdmin/standard_layout.html.twig'
    dashboard:
        groups:
            sonata.admin.group.users:
                keep_open:            true
                label:                'Пользователи'
                icon:                 '<i class="fa fa-user"></i>'
                items:
                    - admin.user
#                    - admin.user_role
                    - route: taasdfadsgahsfdhasdfhafhd
                      label: 'Тестовый кастомный контроллер'