app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options:
        expose: true

sonata_admin_custom:
    resource: "@AppBundle/Controller/SonataAdmin/Custom/"
    type:     annotation
    prefix:   /admin/sonata/custom
    options:
        expose: true