# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.unique_token_generator:
        class: AppBundle\Services\UniqueTokenGenerator
        arguments: ["@service_container"]

    app.user_helper:
        class: AppBundle\Services\UserHelper
        arguments: ["@service_container", "@app.manager.user_manager"]

    # Базовый класс менеджеров
    app.manager.manager_abstract:
        class: AppBundle\Manager\AppManagerAbstract
        abstract:  true
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    # Менеджер торрентов
    app.manager.torrent_manager:
        class: AppBundle\Manager\TorrentManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    # Менеджер пользователей
    app.manager.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]