# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.unique_token_generator:
        class: AppBundle\Services\UniqueTokenGenerator
        arguments: ["@service_container"]

    app.user_helper:
        class: AppBundle\Services\UserHelper
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]